name: Hola Mundo Workflow

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Saludar
        run: echo "¡Hola Mundo desde GitHub Actions!"
